### ISSUE TITLE
[BUG] - testdeck/testdeck-jest-seed is failing build

### ISSUE THREAD

**Issue by silkentrance** [testdeck/testdeck#258]
The travis build for testdeck-jest-seed is failing, see https://travis-ci.org/testdeck/testdeck-jest-seed.

node v13.6.0

```
TypeError: Cannot read property 'length' of null
    at new SearchSource (/home/travis/build/testdeck/testdeck-jest-seed/node_modules/@jest/core/build/SearchSource.js:186:26)
    at /home/travis/build/testdeck/testdeck-jest-seed/node_modules/@jest/core/build/runJest.js:189:22
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/travis/build/testdeck/testdeck-jest-seed/node_modules/@jest/core/build/runJest.js:148:24)
    at _next (/home/travis/build/testdeck/testdeck-jest-seed/node_modules/@jest/core/build/runJest.js:168:9)
    at /home/travis/build/testdeck/testdeck-jest-seed/node_modules/@jest/core/build/runJest.js:173:7
    at new Promise (<anonymous>)
    at /home/travis/build/testdeck/testdeck-jest-seed/node_modules/@jest/core/build/runJest.js:165:12
    at getTestPaths (/home/travis/build/testdeck/testdeck-jest-seed/node_modules/@jest/core/build/runJest.js:223:19)
    at /home/travis/build/testdeck/testdeck-jest-seed/node_modules/@jest/core/build/runJest.js:317:37
```

**Comment by silkentrance** [comment]
fixed by removing the test pattern = null configuration setting in the jest config, which was formerly required by ts-jest.
